---
repos:
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen check
        entry: poetry run cz
        args: ["check", "--allow-abort", "--commit-msg-file"]
        stages: ["commit-msg"]
        language: system
      - id: commitizen-branch
        name: commitizen check branch
        entry: poetry run cz
        args: ["check", "--rev-range", "origin/HEAD..HEAD"]
        always_run: true
        pass_filenames: false
        language: system
        stages: [push]
